### ISSUE TITLE
在qq群发送消息出现的bug

### ISSUE THREAD

**Issue by yuanshuai2017** [hx-w/message-channel#18]
按照文档的方式搭建了消息部署通道，并加入了qqchat.xms.但只能在游戏内发送信息至qq群，qq群发送信息到游戏两边都会挂掉，变成提示:消息发送失败：send message error: [qq group/server is not registed]。以下是ms-core日志截图
![)_H~8_@VYJ_N)T(}8%%YNA8](https://user-images.githubusercontent.com/30584914/145612033-178f1ba6-ecf4-4779-b788-c7b786face11.png)
![}TXYNV%L5GVYM$EIRD W0}N](https://user-images.githubusercontent.com/30584914/145612094-69fad7a6-5b16-44c5-ac22-26bfed8fef0c.png)
![0U )~YXOGVRFG7((MTGQIT1](https://user-images.githubusercontent.com/30584914/145612162-df79a4c5-e87c-4c3d-8892-af244b3bdd75.png)
![0U ~@V%QVGG $N(73JJ(0FF](https://user-images.githubusercontent.com/30584914/145612208-7d8d8ec2-c81c-4a53-a206-03d0a6ec93de.png)
![J6V`35 703G_$@8 U M_L`L](https://user-images.githubusercontent.com/30584914/145612270-c3a59177-5d23-4e9f-8fc9-789cfb8625e5.png)

**Comment by hx-w** [comment]
可能原因：CSGO服务器的54321 tcp端口（由qqchat.cfg中的`mc_port`指定）没有开放至公网
从日志看出游戏向qq可以发送消息，而qq向游戏发送失败。消息通道认为消息发送超时意味着对应游戏服务器不存在，会强制注销对应服务器的记录
