### ISSUE TITLE
功能改进建议

### ISSUE THREAD

**Issue by kevin-zone** [hx-w/message-channel#9]
1.状态指令可以查看服务器玩家名称
2.QQ群推送至服务器的消息应该为群昵称而不是QQ昵称
3.添加ConVar，选择是否显示 "消息推送成功"提示消息

**Comment by hx-w** [comment]
1. 当服务器玩家较多时，在qq群中输出玩家详细内容会占用大量篇幅，且发送长内容容易造成bot风控。暂定使用文字渲染成图片输出的方式解决该问题，还在解决中。
2. 已解决：#8 。默认使用消息发送者的群昵称，如果群昵称不存在则使用qq昵称。`git pull`更新代码 `docker restart mc-nonebot`重启nonebot容器即可。
3. 功能并不复杂，但是需要对更改后的插件充分测试，在国庆假期前应该会发新的sourcemod插件版本。

**Comment by hx-w** [comment]
#11 解决提出的问题，其中**状态**指令查询服务器玩家名称功能会在后需进一步完善，目前只是输出了玩家列表
